/*
===================
database exploration
===================
*/

--explore all objects in the database
select * from INFORMATION_SCHEMA.TABLES



--explore all columns in the database

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'

/*
===================
dims exploration
===================
*/
--explore all countries our customer come from

select distinct country from gold.dim_customers

--explore all cat 
select distinct category,subcategory,product_name
from gold.dim_products
order by 1,2,3

/*
===================
date exploration
===================
*/
--first_order & first_order & order_range_date
select MIN(order_date) first_order,
 max(order_date) last_order,
datediff(YEAR ,MIN(order_date), max(order_date)) order_range_date
from gold.fact_sales

--find youngest & oldest customer

select min(birthdate),
max(birthdate),
datediff(year,min(birthdate),GETDATE()),
datediff(year,max(birthdate),GETDATE())
from gold.dim_customers

/*
===================
measures exploration
===================
*/
--find the total sales

select sum(sales_amount) as total_sales
from gold.fact_sales

--find how many items are sold
select sum(quantity)
from gold.fact_sales

--fid the average selling price
select AVG(price) 
from gold.fact_sales
--find the total num of orders
select count(distinct order_number)
from gold.fact_sales

--find the total num of products
select count(distinct product_number)
from gold.dim_products
--find the total num of customers
select count( customer_number)
from gold.dim_customers
--find the total num of customers that has placed an order

select count(distinct customer_number)
from gold.dim_customers

/*
===================
magnitude exploration
===================
*/
--find total customers by countries ?
select distinct country,
count(customer_key) as total_customer_by_gender
from gold.dim_customers
group by country

--find total customers by gender ?
select distinct gender,
count(customer_key) as total_customer_by_gender
from gold.dim_customers
group by gender
--find total products by category ?
select category,
COUNT(product_key) as total_sales_by_cat
from gold.dim_products
group by category
--avg cost in each category ?
SELECT category,
AVG(cost) as avg_sales_by_cat
FROM gold.dim_products
group by category
--the total revenue is generated for each category ?
select p.category,
SUM(fs.sales_amount) as sales_amount
from gold.fact_sales as fs
left join gold.dim_products as p
on p.product_key = fs.product_key
group by p.category 

--find total revenue is generated by each customer ?
select c.customer_key,
c.first_name,
c.last_name,
SUM(fs.sales_amount) as sales_amount
from gold.fact_sales as fs
left join gold.dim_customers as c
on c.customer_key = fs.customer_key
group by c.customer_key,
c.first_name,
c.last_name
--what od the distribution of sold items accross countries ?

select c.country,
SUM(fs.sales_amount) as sales_amount
from gold.fact_sales as fs
left join gold.dim_customers as c
on c.customer_key = fs.customer_key
group by c.country

/*
===================
Ranking exploration
===================
*/
--generate the top 5 products that have high revenue

select top (5) p.product_name,
SUM(fs.sales_amount) as sales_amount
from gold.fact_sales as fs
left join gold.dim_products as p
on p.product_key = fs.product_key
group by p.product_name
order by sales_amount desc

--generate the worst 5 products that have high revenue

select top (5) p.product_name,
SUM(fs.sales_amount) as sales_amount
from gold.fact_sales as fs
left join gold.dim_products as p
on p.product_key = fs.product_key
group by p.product_name
order by sales_amount
--------------------------------------------------
select product_name,
sales_amount
from (
select p.product_name,
SUM(fs.sales_amount) as sales_amount,
ROW_NUMBER()over(order by SUM(fs.sales_amount)) as rank
from gold.fact_sales as fs
left join gold.dim_products as p
on p.product_key = fs.product_key
group by p.product_name
)t
where rank <=5

